#!/usr/bin/env python3

'''
sudo cp ./comps/probing /usr/bin/


'''

import hal
import linuxcnc

class Comp:
    def __init__(self, name):
        self.comp = hal.component(name)
        self.command = linuxcnc.command()
        self.bit_input = ['start', ]
        self.float_input = []
        self.bit_output = []
        self.float_output = []
        
        self.setup_pins()

    def setup_pins(self):
        for pin_name in self.bit_input:
            self.comp.newpin(pin_name, hal.HAL_BIT, hal.HAL_IN)
        
        for pin_name in self.float_input:
            self.comp.newpin(pin_name, hal.HAL_FLOAT, hal.HAL_IN)

        for pin_name in self.bit_output:
            self.comp.newpin(pin_name, hal.HAL_BIT, hal.HAL_OUT)
        
        for pin_name in self.float_output:
            self.comp.newpin(pin_name, hal.HAL_FLOAT, hal.HAL_OUT)
    
    def ready(self):
        self.comp.ready()
        
    def operation(self):
        while self.comp['start']:
            self.command.mode(linuxcnc.MODE_MDI)
            self.command.wait_complete()
            self.command.mdi('M65P0')
            
            
        
    
if __name__ == "__main__":
    probing = Comp('probing')
    probing.ready()
    probing.operation()
    
    

    while 1:
        try:
            probing.operation()
        except Exception as e:
            print(f"An exception occurred: {e}")
  