#!/usr/bin/env python3

'''
sudo cp ./comps/probing /usr/bin/
'''

import hal
import linuxcnc
import time



comp = hal.component('probing')
command = linuxcnc.command()

bit_input = ['start', ]
float_input = []
bit_output = []
float_output = []

for pin_name in bit_input:
    comp.newpin(pin_name, hal.HAL_BIT, hal.HAL_IN)

for pin_name in float_input:
    comp.newpin(pin_name, hal.HAL_FLOAT, hal.HAL_IN)

for pin_name in bit_output:
    comp.newpin(pin_name, hal.HAL_BIT, hal.HAL_OUT)

for pin_name in float_output:
    comp.newpin(pin_name, hal.HAL_FLOAT, hal.HAL_OUT)
    
comp.ready()

def probe():
    command.mdi('G91')
    command.mdi('G38.3 Z-50 F750')
    command.mdi('G0 Z5')
    command.mdi('M03 S100')
    command.mdi('M66 P0 L3 Q5')
    command.mdi('G0 Z3')
    command.mdi('G90')
    command.mdi('G04 P3')
    command.mdi('M65P0')

try:
    while True:        
        if comp.start:
            probe()
        else:
            pass
except KeyboardInterrupt:
    raise SystemExit
    

  