component thc2 "Height Control Up/Down Input";

license "GPLv2 or greater";

option singleton yes;

pin in float in_volts_meas          "Volts measured from plasma";
pin in float in_volts_coef          "Volts coefficient";
pin in float in_volts_setup         "Volts setup. From GUI";
pin in float in_hall_volts          "hall sensor volage";
pin in float in_hall_volts_setup    "hall sensor volage setup";

pin out bit arc_ok_status           "Arc OK status";
pin out bit thcu                    "THC up";
pin out bit thcd                    "THC down";

pin out float volts                 "The Calculated Volts for GUI";

//param rw float hall_sens_set "hall sensor volage setup";

function _;

;;

FUNCTION(_) {
    volts = in_volts_meas * in_volts_coef;

    if (in_hall_volts > in_hall_volts_setup){
        arc_ok_status = 1;
    } else {
        arc_ok_status = 0;
    }

    if (volts < in_volts_setup){
        thcu = 1;
        thcd = 0;
    } else if (volts > in_volts_setup){
        thcu = 0;
        thcd = 1;
    } else {
        thcu = 0;
        thcd = 0;
    }

}

