component z_control "Hiden control for axiz Z";

description 
"""

""";
 
author "ddd";

license "GPLv2 or greater";

option singleton yes;

// Input Pins
pin in bit 		up "Up pin";
pin in bit 		down "Down pin";

pin in float 	velocity "Velocity";
pin in float 	scale "Scale for velocity";
pin in float	z_pos_cmd_in "Z pos in from joint.*.motor-pos-cmd";
pin in float	z_pos_fb_in "Z pos fb from stepgen.*.position-fb";

// Output Pins
pin out float 	z_pos_cmd_out "To stepgen.*.position-cmd";
pin out float 	z_pos_fb_out "Z Position Feedback to Axis";

// Global Variables
variable float offset;
variable float cor_vel;

function _;

;;

#include "rtapi_math.h"

FUNCTION(_) {
	cor_vel = velocity * scale;
	if(up){
		offset += cor_vel;
	}
	if(down){
		offset -= cor_vel;
	}
	z_pos_cmd_out = z_pos_cmd_in + offset;
	z_pos_fb_out = z_pos_cmd_in;
	}	